apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
        name: TEST
        namespace: argocd
spec:
        project: default
        source:
                repoURL: https://github.com/nadeemshahzad/argocd-testing.git
                targetRevision: HEAD
                path: .
        destination:
                server: https://kubernetes.default.svc
                namespace: TEST
        syncPolicy:
                automated: true
                prune: true
                selfHeal: true
